### ISSUE TITLE
Deprecation of the Python CLI

### ISSUE THREAD

**Issue by w3bb** [int-72h/of-jam#14]
The CLI in this repository is in a bit of a sad state. At best it could be seen as a reference implementation. It's missing features like threading, and is overall not worth using. Most of the work I've put into TVN lately is on [murse](https://spiderden.net/projects/murse), a reimplementation of that with proper concurrency and more robust code. I think instead of trying to fix the Python CLI we should deprecate it in favour of murse or another community TVN client.

**Comment by int-72h** [comment]
I think that the python one should be fixed purely to remain a reference implementation, but the use of murse should be encouraged.
