### ISSUE TITLE
Errors relating to Windows 7?

### ISSUE THREAD

**Issue by loop4321** [int-72h/of-jam#7]
I tried to open oftoast.exe and got these errors.
![error1](https://user-images.githubusercontent.com/106642515/171320671-14a535f5-f861-4646-b8a3-ffecbe821ff5.png)
![error2](https://user-images.githubusercontent.com/106642515/171320676-8d2fa219-a2ec-4edf-8793-151a0b91d20b.png)

Someone in the discord said the problem could be that the program is compiled without Win7 support, and that I should make a bug report about it.

**Comment by int-72h** [comment]
Yeah, the windows executable was packaged on 10. A windows 7 version is coming soon.

**Comment by loop4321** [comment]
> Yeah, the windows executable was packaged on 10. A windows 7 version is coming soon.

Wonderful!

**Comment by int-72h** [comment]
it's now able to run on windows 7.
